### PR TITLE
Report file optional again

### PR DESCRIPTION
**Pull request by michalkot**
Having an option to set the report file location is very important for us. By default report file is being generated in the same location as the compiled js. In our case that directory is for production deployment and we can't have log files there.

Building on LeZuse pull request #24, but leaving the default as it used to be. So: by default it generates the report in the same location. You may provide a custom reportFile path to save it in, say, your log directory. You may also set

``` javascript
reportFile: ''
```

to not log at all. In this case it does seem useful to log errors to console.

### CODE REVIEW

**Comment by gmarty** [comment]
Can you do it the other way around? That is having an option to deactivate the report (i.e. `noreport`)?
When done I'll merge in and republish to npm.

**Comment by michalkot** [comment]
Updated. Now: `reportFile` is an option to customize report location (if not specified still generates in default location like it used to).
Plus there is an option `noreport` as suggested to skip report file creation but still print `min_info`

**Comment by michalkot** [comment]
This works like it used to:

``` javascript
grunt.initConfig({
  'closure-compiler': {
    frontend: {
      closurePath: '/src/to/closure-compiler',
      js: 'static/src/frontend.js',
      jsOutputFile: 'static/js/frontend.min.js',
      maxBuffer: 500,
      options: {
        compilation_level: 'ADVANCED_OPTIMIZATIONS',
        language_in: 'ECMASCRIPT5_STRICT'
      }
    }
  }
});
```

This saves report in log/compile.log

``` javascript
grunt.initConfig({
  'closure-compiler': {
    frontend: {
      closurePath: '/src/to/closure-compiler',
      js: 'static/src/frontend.js',
      jsOutputFile: 'static/js/frontend.min.js',
      reportFile: 'log/compile.log',
      maxBuffer: 500,
      options: {
        compilation_level: 'ADVANCED_OPTIMIZATIONS',
        language_in: 'ECMASCRIPT5_STRICT'
      }
    }
  }
});
```

This prevents generating log file:

``` javascript
grunt.initConfig({
  'closure-compiler': {
    frontend: {
      closurePath: '/src/to/closure-compiler',
      js: 'static/src/frontend.js',
      jsOutputFile: 'static/js/frontend.min.js',
      noreport: true,
      maxBuffer: 500,
      options: {
        compilation_level: 'ADVANCED_OPTIMIZATIONS',
        language_in: 'ECMASCRIPT5_STRICT'
      }
    }
  }
});
```

**Comment by gmarty** [comment]
All merged and published now. Thanks guys for your help!

**Pull request merged**
